services:
  watchtower:
    container_name: watchtower
    env_file:
      - data.env
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    image: nickfedor/watchtower
    command: --schedule "0 0 4 * * *"
