services:
  watchtower:
    container_name: watchtower
    environment:
      - TZ=Europe/Budapest
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    image: containrrr/watchtower
    command: --schedule "0 0 4 * * *"
